version: "3.7"

networks:
  local:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: api-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 30000 -b '0.0.0.0'"
    volumes:
      - .:/var/www
    ports:
      - "30000:30000"
    networks:
      - local