# Database Config
DB_ADAPTER: 'postgresql'
DB_DATABASE: ''
DB_USERNAME: ''
DB_PASSWORD: ''
DB_HOST: 'localhost'
DB_PORT: '5432'
DB_POOL: '5'

# Redis Config
REDIS_HOST: '127.0.0.1'
REDIS_PORT: '6380'
REDIS_USERNAME: ''
REDIS_PASSWORD: ''

# JWT
JWT_SECRET: 'rails-4p!-s3cer3tS'