connection: &connection
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: utf8
  pool: <%= ENV['DB_POOL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *connection
  database: <%= ENV['DB_DATABASE'] %>

test:
  <<: *connection
  database: <%= ENV['DB_DATABASE'] %>

production:
  <<: *connection
  database: <%= ENV['DB_DATABASE'] %>